version: '3'
services:
  notebook:
    build:
      context: ./jupyter_notebook_docker
    ports:
      - "8888:8888"
    depends_on: 
      - mlflow
    environment: 
      MLFLOW_TRACKING_URI: 'http://mlflow:5000'
    volumes: 
      - ./project:/usr/src
  mlflow:
    build:
      context: ./ml_flow_docker
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
  postgres:
    build:
      context: ./postgres_docker
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'secret'
    ports: 
      - "5432:5432"
    volumes:
      - postgres-store:/var/lib/postgresql/data
    # environment:
    #   PGDATA: /tmp
  # airflow:
  #   image: puckel/docker-airflow
  #   restart: always
  #   environment:
  #     - LOAD_EX=n
  #     - EXECUTOR=Local
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #   - ./dags:/usr/local/airflow/dags
  #   command: webserver

volumes:
  postgres-store:

#   file-store: